USE [master]
GO

CREATE DATABASE [Demo_HR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Demo_HR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Demo_HR.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Demo_HR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Demo_HR_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

/*
ALTER DATABASE [Demo_HR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Demo_HR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Demo_HR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Demo_HR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Demo_HR] SET ARITHABORT OFF 
GO
ALTER DATABASE [Demo_HR] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Demo_HR] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Demo_HR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Demo_HR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Demo_HR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Demo_HR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Demo_HR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Demo_HR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Demo_HR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Demo_HR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Demo_HR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Demo_HR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Demo_HR] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Demo_HR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Demo_HR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Demo_HR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Demo_HR] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Demo_HR] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Demo_HR] SET  MULTI_USER 
GO
ALTER DATABASE [Demo_HR] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Demo_HR] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Demo_HR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Demo_HR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Demo_HR] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Demo_HR] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Demo_HR] SET QUERY_STORE = OFF
GO
ALTER DATABASE [Demo_HR] SET  READ_WRITE 
GO
*/
