USE Demo_HR;

CREATE TABLE Demo_HR.JOBS 
   (JOB_ID VARCHAR(10), 
	JOB_TITLE VARCHAR(35) NOT NULL, 
	MIN_SALARY NUMERIC(6,0), 
	MAX_SALARY NUMERIC(6,0), 
	 CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID)
   );



-- Demo_HR..JOBS_SNAPSHOT definition
CREATE TABLE Demo_HR.JOBS_SNAPSHOT 
   (JOB_ID VARCHAR(10), 
	JOB_TITLE VARCHAR(35) NOT NULL, 
	MIN_SALARY NUMERIC(6,0), 
	MAX_SALARY NUMERIC(6,0)
   );


  
-- Demo_HR..REGIONS definition
CREATE TABLE Demo_HR.REGIONS 
   (REGION_ID INTEGER NOT NULL PRIMARY KEY, 
	REGION_NAME VARCHAR(25) 
   );



-- Demo_HR..COUNTRIES definition
CREATE TABLE Demo_HR.COUNTRIES 
   (COUNTRY_ID CHAR(2) NOT NULL PRIMARY KEY, 
	COUNTRY_NAME VARCHAR(40), 
	REGION_ID NUMERIC REFERENCES Demo_HR.REGIONS (REGION_ID), 
	DATE_LAST_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP 
   );




-- Demo_HR..LOCATIONS definition
CREATE TABLE Demo_HR.LOCATIONS 
   (LOCATION_ID NUMERIC(4,0) PRIMARY KEY,  
	STREET_ADDRESS VARCHAR(40), 
	POSTAL_CODE VARCHAR(12), 
	CITY VARCHAR(30) NOT NULL, 
	STATE_PROVINCE VARCHAR(25), 
	COUNTRY_ID CHAR(2) REFERENCES Demo_HR.COUNTRIES (COUNTRY_ID)
   );

CREATE INDEX LOC_CITY_IX ON Demo_HR.LOCATIONS (CITY);
CREATE INDEX LOC_STATE_PROVINCE_IX ON Demo_HR.LOCATIONS (STATE_PROVINCE);
CREATE INDEX LOC_COUNTRY_IX ON Demo_HR.LOCATIONS (COUNTRY_ID);



-- Demo_HR..DEPARTMENTS definition
CREATE TABLE Demo_HR.DEPARTMENTS 
   (DEPARTMENT_ID NUMERIC(4,0) PRIMARY KEY, 
	DEPARTMENT_NAME VARCHAR(30) NOT NULL, 
	MANAGER_ID NUMERIC(6,0), 
	LOCATION_ID NUMERIC(4,0) REFERENCES Demo_HR.LOCATIONS (LOCATION_ID) ,
	URL VARCHAR(255) 
   ) ;

CREATE INDEX DEPT_LOCATION_IX ON Demo_HR.DEPARTMENTS (LOCATION_ID);



-- Demo_HR..JOB_HISTORY definition
CREATE TABLE Demo_HR.JOB_HISTORY 
   (EMPLOYEE_ID NUMERIC(6,0) NOT NULL, 
	START_DATE DATETIME NOT NULL, 
	END_DATE DATETIME NOT NULL, 
	JOB_ID VARCHAR(10) NOT NULL, 
	DEPARTMENT_ID NUMERIC(4,0), 
	 CONSTRAINT JHIST_DATE_INTERVAL CHECK (end_date > start_date), 
	 CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID, START_DATE), 
	 CONSTRAINT JHIST_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES Demo_HR.JOBS (JOB_ID), 
	 CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES Demo_HR.DEPARTMENTS (DEPARTMENT_ID)
   ) ;

CREATE INDEX JHIST_JOB_IX ON Demo_HR.JOB_HISTORY (JOB_ID);
CREATE INDEX JHIST_EMPLOYEE_IX ON Demo_HR.JOB_HISTORY (EMPLOYEE_ID);
CREATE INDEX JHIST_DEPARTMENT_IX ON Demo_HR.JOB_HISTORY (DEPARTMENT_ID);




-- Demo_HR..EMPLOYEES definition
CREATE TABLE Demo_HR.EMPLOYEES 
   (EMPLOYEE_ID NUMERIC(6,0), 
	FIRST_NAME VARCHAR(20), 
	LAST_NAME VARCHAR(25) NOT NULL, 
	EMAIL VARCHAR(25) NOT NULL, 
	PHONE_NUMBER VARCHAR(20), 
	HIRE_DATE DATETIME NOT NULL, 
	JOB_ID VARCHAR(10) NOT NULL, 
	SALARY NUMERIC(8,2), 
	COMMISSION_PCT NUMERIC(2,2), 
	MANAGER_ID NUMERIC(6,0), 
	DEPARTMENT_ID NUMERIC(4,0), 
	SOME_DATE_FMT1 VARCHAR(50), 
	SOME_DATE_FMT2 VARCHAR(50), 
	SOME_DATE_FMT3 VARCHAR(50), 
	SOME_DATE_FMT4 VARCHAR(50), 
	FAKE_SSN VARCHAR(11), 
	ZIP5 VARCHAR(5), 
	ZIP5OR9 VARCHAR(10), 
	ZIP9 VARCHAR(10), 
	EMAIL_ADDRESS VARCHAR(100), 
	 CONSTRAINT EMP_SALARY_MIN CHECK (salary > 0), 
	 CONSTRAINT EMP_EMAIL_UK UNIQUE (EMAIL), 
	 CONSTRAINT EMP_EMP_ID_PK PRIMARY KEY (EMPLOYEE_ID), 
	 CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES Demo_HR.DEPARTMENTS (DEPARTMENT_ID), 
	 CONSTRAINT EMP_JOB_FK FOREIGN KEY (JOB_ID) REFERENCES Demo_HR.JOBS (JOB_ID), 
	 CONSTRAINT EMP_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES Demo_HR.EMPLOYEES (EMPLOYEE_ID)
   ) ;

CREATE INDEX EMP_DEPARTMENT_IX ON Demo_HR.EMPLOYEES (DEPARTMENT_ID);
CREATE INDEX EMP_JOB_IX ON Demo_HR.EMPLOYEES (JOB_ID);
CREATE INDEX EMP_MANAGER_IX ON Demo_HR.EMPLOYEES (MANAGER_ID);
CREATE INDEX EMP_NAME_IX ON Demo_HR.EMPLOYEES (LAST_NAME, FIRST_NAME);






