CREATE USER DEMO_HR IDENTIFIED BY DEMO_HR; 

GRANT UNLIMITED TABLESPACE TO DEMO_HR;



-- DEMO_HR.JOBS definition
CREATE TABLE "DEMO_HR"."JOBS" 
   ("JOB_ID" VARCHAR2(10), 
	"JOB_TITLE" VARCHAR2(35) CONSTRAINT "JOB_TITLE_NN" NOT NULL ENABLE, 
	"MIN_SALARY" NUMBER(6,0), 
	"MAX_SALARY" NUMBER(6,0), 
	 CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID") ENABLE
   );



-- DEMO_HR.JOBS_SNAPSHOT definition
CREATE TABLE "DEMO_HR"."JOBS_SNAPSHOT" 
   ("JOB_ID" VARCHAR2(10), 
	"JOB_TITLE" VARCHAR2(35) NOT NULL ENABLE, 
	"MIN_SALARY" NUMBER(6,0), 
	"MAX_SALARY" NUMBER(6,0)
   );


  
-- DEMO_HR.REGIONS definition
CREATE TABLE "DEMO_HR"."REGIONS" 
   ("REGION_ID" NUMBER CONSTRAINT "REGION_ID_NN" NOT NULL ENABLE, 
	"REGION_NAME" VARCHAR2(25), 
	 CONSTRAINT "REG_ID_PK" PRIMARY KEY ("REGION_ID") ENABLE
   );



-- DEMO_HR.COUNTRIES definition
CREATE TABLE "DEMO_HR"."COUNTRIES" 
   ("COUNTRY_ID" CHAR(2) CONSTRAINT "COUNTRY_ID_NN" NOT NULL ENABLE, 
	"COUNTRY_NAME" VARCHAR2(40), 
	"REGION_ID" NUMBER, 
	"DATE_LAST_UPDATED" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "COUNTRY_C_ID_PK" PRIMARY KEY ("COUNTRY_ID") ENABLE, 
	 CONSTRAINT "COUNTR_REG_FK" FOREIGN KEY ("REGION_ID") REFERENCES "DEMO_HR"."REGIONS" ("REGION_ID") ENABLE
   );




-- DEMO_HR.LOCATIONS definition
CREATE TABLE "DEMO_HR"."LOCATIONS" 
   ("LOCATION_ID" NUMBER(4,0), 
	"STREET_ADDRESS" VARCHAR2(40), 
	"POSTAL_CODE" VARCHAR2(12), 
	"CITY" VARCHAR2(30) CONSTRAINT "LOC_CITY_NN" NOT NULL ENABLE, 
	"STATE_PROVINCE" VARCHAR2(25), 
	"COUNTRY_ID" CHAR(2), 
	 CONSTRAINT "LOC_ID_PK" PRIMARY KEY ("LOCATION_ID") ENABLE, 
	 CONSTRAINT "LOC_C_ID_FK" FOREIGN KEY ("COUNTRY_ID") REFERENCES "DEMO_HR"."COUNTRIES" ("COUNTRY_ID") ENABLE
   );

CREATE INDEX "DEMO_HR"."LOC_CITY_IX" ON "DEMO_HR"."LOCATIONS" ("CITY");
CREATE INDEX "DEMO_HR"."LOC_STATE_PROVINCE_IX" ON "DEMO_HR"."LOCATIONS" ("STATE_PROVINCE");
CREATE INDEX "DEMO_HR"."LOC_COUNTRY_IX" ON "DEMO_HR"."LOCATIONS" ("COUNTRY_ID");



-- DEMO_HR.DEPARTMENTS definition
CREATE TABLE "DEMO_HR"."DEPARTMENTS" 
   ("DEPARTMENT_ID" NUMBER(4,0), 
	"DEPARTMENT_NAME" VARCHAR2(30) CONSTRAINT "DEPT_NAME_NN" NOT NULL ENABLE, 
	"MANAGER_ID" NUMBER(6,0), 
	"LOCATION_ID" NUMBER(4,0), 
	"URL" VARCHAR2(255), 
	 CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPARTMENT_ID") ENABLE, 
	 CONSTRAINT "DEPT_LOC_FK" FOREIGN KEY ("LOCATION_ID") REFERENCES "DEMO_HR"."LOCATIONS" ("LOCATION_ID") ENABLE 
   ) ;

CREATE INDEX "DEMO_HR"."DEPT_LOCATION_IX" ON "DEMO_HR"."DEPARTMENTS" ("LOCATION_ID");



-- DEMO_HR.JOB_HISTORY definition
CREATE TABLE "DEMO_HR"."JOB_HISTORY" 
   ("EMPLOYEE_ID" NUMBER(6,0) CONSTRAINT "JHIST_EMPLOYEE_NN" NOT NULL ENABLE, 
	"START_DATE" DATE CONSTRAINT "JHIST_START_DATE_NN" NOT NULL ENABLE, 
	"END_DATE" DATE CONSTRAINT "JHIST_END_DATE_NN" NOT NULL ENABLE, 
	"JOB_ID" VARCHAR2(10) CONSTRAINT "JHIST_JOB_NN" NOT NULL ENABLE, 
	"DEPARTMENT_ID" NUMBER(4,0), 
	 CONSTRAINT "JHIST_DATE_INTERVAL" CHECK (end_date > start_date) ENABLE, 
	 CONSTRAINT "JHIST_EMP_ID_ST_DATE_PK" PRIMARY KEY ("EMPLOYEE_ID", "START_DATE") ENABLE, 
	 CONSTRAINT "JHIST_JOB_FK" FOREIGN KEY ("JOB_ID") REFERENCES "DEMO_HR"."JOBS" ("JOB_ID") ENABLE, 
	 CONSTRAINT "JHIST_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEMO_HR"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE
   ) ;

CREATE INDEX "DEMO_HR"."JHIST_JOB_IX" ON "DEMO_HR"."JOB_HISTORY" ("JOB_ID");
CREATE INDEX "DEMO_HR"."JHIST_EMPLOYEE_IX" ON "DEMO_HR"."JOB_HISTORY" ("EMPLOYEE_ID");
CREATE INDEX "DEMO_HR"."JHIST_DEPARTMENT_IX" ON "DEMO_HR"."JOB_HISTORY" ("DEPARTMENT_ID");




-- DEMO_HR.EMPLOYEES definition
CREATE TABLE "DEMO_HR"."EMPLOYEES" 
   ("EMPLOYEE_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(20), 
	"LAST_NAME" VARCHAR2(25) CONSTRAINT "EMP_LAST_NAME_NN" NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(25) CONSTRAINT "EMP_EMAIL_NN" NOT NULL ENABLE, 
	"PHONE_NUMBER" VARCHAR2(20), 
	"HIRE_DATE" DATE CONSTRAINT "EMP_HIRE_DATE_NN" NOT NULL ENABLE, 
	"JOB_ID" VARCHAR2(10) CONSTRAINT "EMP_JOB_NN" NOT NULL ENABLE, 
	"SALARY" NUMBER(8,2), 
	"COMMISSION_PCT" NUMBER(2,2), 
	"MANAGER_ID" NUMBER(6,0), 
	"DEPARTMENT_ID" NUMBER(4,0), 
	"SOME_DATE_FMT1" VARCHAR2(50), 
	"SOME_DATE_FMT2" VARCHAR2(50), 
	"SOME_DATE_FMT3" VARCHAR2(50), 
	"SOME_DATE_FMT4" VARCHAR2(50), 
	"FAKE_SSN" VARCHAR2(11), 
	"ZIP5" VARCHAR2(5), 
	"ZIP5OR9" VARCHAR2(10), 
	"ZIP9" VARCHAR2(10), 
	"EMAIL_ADDRESS" VARCHAR2(100), 
	 CONSTRAINT "EMP_SALARY_MIN" CHECK (salary > 0) ENABLE, 
	 CONSTRAINT "EMP_EMAIL_UK" UNIQUE ("EMAIL") ENABLE, 
	 CONSTRAINT "EMP_EMP_ID_PK" PRIMARY KEY ("EMPLOYEE_ID") ENABLE, 
	 CONSTRAINT "EMP_DEPT_FK" FOREIGN KEY ("DEPARTMENT_ID") REFERENCES "DEMO_HR"."DEPARTMENTS" ("DEPARTMENT_ID") ENABLE, 
	 CONSTRAINT "EMP_JOB_FK" FOREIGN KEY ("JOB_ID") REFERENCES "DEMO_HR"."JOBS" ("JOB_ID") ENABLE, 
	 CONSTRAINT "EMP_MANAGER_FK" FOREIGN KEY ("MANAGER_ID") REFERENCES "DEMO_HR"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE
   ) ;

CREATE INDEX "DEMO_HR"."EMP_DEPARTMENT_IX" ON "DEMO_HR"."EMPLOYEES" ("DEPARTMENT_ID");
CREATE INDEX "DEMO_HR"."EMP_JOB_IX" ON "DEMO_HR"."EMPLOYEES" ("JOB_ID");
CREATE INDEX "DEMO_HR"."EMP_MANAGER_IX" ON "DEMO_HR"."EMPLOYEES" ("MANAGER_ID");
CREATE INDEX "DEMO_HR"."EMP_NAME_IX" ON "DEMO_HR"."EMPLOYEES" ("LAST_NAME", "FIRST_NAME");






